---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-master
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-cache-redis-master
  name: cache-redis-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-cache-redis-master
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-cache-redis-master
    spec:
      containers:
      - env:
        - name: MASTER_GROUP_NAME
          value: redis-cache-master
        - name: NAMESPACE
          value: source-data-redis
        - name: REDIS_SVC
          value: 172.9.84.112
        - name: RELEASE
          value: cache-redis
        - name: SLEEP_TIME
          value: 30
        image: asteroidning/redis-master:1.0
        imagePullPolicy: Always
        name: redis-master
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: redis-master
      serviceAccountName: redis-master
      terminationGracePeriodSeconds: 30
